# Generated by Django 5.2.7 on 2025-10-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
