# Generated by Django 5.2.7 on 2025-10-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=50, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentación',
            },
        ),
        migrations.CreateModel(
            name='UdM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_de_medida', models.CharField(max_length=20, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=5, unique=True)),
                ('categoria', models.CharField(max_length=60, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
                'constraints': [models.UniqueConstraint(fields=('partida', 'categoria'), name='unique_partida_categoria')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('nivel_minimo', models.PositiveIntegerField(default=5)),
                ('cantidad_existente', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.partidapresupuestaria')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.presentacion')),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.udm')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
