# Generated by Django 5.2.7 on 2025-10-15 05:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['rol'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=25)),
                ('apellido_materno', models.CharField(blank=True, max_length=25, null=True)),
                ('usuario_activo', models.BooleanField()),
                ('usuario_admin', models.BooleanField(default=False)),
                ('alta', models.DateField(auto_now_add=True)),
                ('baja', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_usuarios', to='usuarios.cargo')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['nombre', 'apellido_paterno'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_departamento', to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_rol', to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_unidad', to='usuarios.unidad'),
        ),
        migrations.CreateModel(
            name='UsuarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_estado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Usuario',
                'verbose_name_plural': 'Logs de Usuarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido_paterno', 'apellido_materno'), name='unique_nombre_apellidos'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('cargo', 'departamento', 'unidad'), name='unique_cargo_departamento_unidad'),
        ),
    ]
