# Generated by Django 5.2.7 on 2025-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
    ]
