# Generated by Django 5.2.7 on 2025-10-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_usuario_activo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargo',
            name='unique_cargo_departamento_unidad',
        ),
    ]
