# Generated by Django 5.2.7 on 2025-10-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_cargo_unique_cargo_departamento_unidad'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('cargo', 'departamento', 'unidad'), name='unique_cargo_departamento_unidad'),
        ),
    ]
