# Generated by Django 5.2.7 on 2025-10-17 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.PositiveSmallIntegerField(default=1)),
                ('cantidad_existente', models.PositiveSmallIntegerField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('nivel_estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.nivelestante')),
            ],
            options={
                'verbose_name': 'Asignacion de Material',
                'verbose_name_plural': 'Asignacion de Materiales',
            },
        ),
    ]
