# Generated by Django 5.2.7 on 2025-10-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionmaterial',
            name='cantidad_existente',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
